# Generated by Django 3.2.8 on 2021-10-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photoling',
        ),
    ]
