# Generated by Django 3.2.8 on 2021-10-14 09:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_image_image_photoling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photoling',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
